import 'package:flutter/foundation.dart';
import 'context_bullet.dart';

/// Single-sentence supportive explanation generated by the on-device SLM or safe fallback.
///
/// See Plans/IMPLEMENTATION.md §4.1 / §4.3 and Plans/frontend_prd.md §4.1.
@immutable
class Explanation {
  const Explanation({
    required this.sentence,
    required this.contextBullets,
    required this.generatedAt,
    this.usedModel = false,
    this.fallbackReason,
  });

  factory Explanation.fromJson(Map<String, dynamic> json) {
    final rawBullets = json['contextBullets'] as List<dynamic>? ?? [];
    return Explanation(
      sentence: json['text'] as String? ?? json['sentence'] as String? ?? '',
      contextBullets: rawBullets
          .map((b) => ContextBullet.fromJson(Map<String, dynamic>.from(b as Map)))
          .toList(),
      generatedAt: DateTime.now(),
      usedModel: json['usedModel'] as bool? ?? false,
      fallbackReason: json['fallbackReason'] as String?,
    );
  }

  final String sentence;
  final List<ContextBullet> contextBullets;
  final DateTime generatedAt;
  final bool usedModel;
  final String? fallbackReason;

  Map<String, dynamic> toJson() => {
    'sentence': sentence,
    'contextBullets': contextBullets.map((b) => b.toJson()).toList(),
    'generatedAt': generatedAt.toIso8601String(),
    'usedModel': usedModel,
    'fallbackReason': fallbackReason,
  };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is Explanation &&
          runtimeType == other.runtimeType &&
          sentence == other.sentence &&
          listEquals(contextBullets, other.contextBullets) &&
          usedModel == other.usedModel &&
          fallbackReason == other.fallbackReason;

  @override
  int get hashCode => Object.hash(
    sentence,
    Object.hashAll(contextBullets),
    usedModel,
    fallbackReason,
  );
}
